spring.application.name=equip-management

# URL kết nối (thay 'ten_database_cua_ban' bằng tên thực tế)
spring.datasource.url=jdbc:mysql://localhost:3306/DrugManagement?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=112358

# Tự động cập nhật cấu trúc bảng từ Entity Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080